name: Publish to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Install Emacs
        run: sudo apt install emacs-nox --yes

      - name: Build the site
        run: ./build.sh
      - name: Publish to GitHub Pages
        # You may pin to the exact commit or the version.
        # uses: tsunematsu21/actions-publish-gh-pages@c04b531c52b8f9d25c596bc6e6a7ddc116b2f3f8
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          # The name of the directory that containing the content to be published
          dir: /public # optional, default is ./
          # The name of the remote branch that publishing source for GitHub Pages site
          branch: # optional, default is gh-pages
          # The remote repository that publishing source for GitHub Pages site, defaults to current repo and is formatted like 'user/repo-name'
          repo: # optional
          # The personal access token that authorize repo access
          token: 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        
