name: Publish to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v1

      - name: Install Emacs
        run: sudo apt install emacs-nox --yes

      - name: Build the site
        run: ./build.sh

      - name: Publish to GitHub Pages Action
        # You may pin to the exact commit or the version.
        # uses: qoomon/actions-publish-to-github-pages@6a40eb09ac8c40658b68467787c0ae58764824c5
        uses: qoomon/actions-publish-to-github-pages@v1.0.3
        with:
          # Source Directory
          GITHUB_PAGES_SOURCE_DIR: public # optional, default is dist
          # GitHub Pages Branch Name
          GITHUB_PAGES_BRANCH: gh-pages # optional, default is gh-pages
          # If set to true this action will replace current GitHub Pages branch
